services:
  app:
    image: ${DOCKERHUB_IMAGE_NAME}:${GITHUB_SHA:-latest}
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env.prod
    networks:
      - app-network

  # Service for the Nginx Reverse Proxy
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - app-network

    # Certbot service for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
