services:
  app:
    image: ${DOCKERHUB_IMAGE_NAME}:${GITHUB_SHA:-latest}
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    env_file:
      - .env.prod
    networks:
      - app_network
    expose:
      - "3000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /opt/certbot/www:/var/www/certbot:ro
    depends_on:
      - app
    networks:
      - app_network
    command: '/bin/sh -c ''while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot:latest
    container_name: certbot_service
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:rw
      - /opt/certbot/www:/var/www/certbot:rw
    entrypoint: sh -c
    command: >
      sh -c "while true; do \
        certbot renew --webroot -w /var/www/certbot --quiet; \
        sleep 12h; \
      done"
    depends_on:
      - nginx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  letsencrypt_certs:
  certbot_www:
